apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-{{.Chart.Name}}-{{.Values.service.name}}-secret
  namespace: {{.Values.namespace.name}}
type: Opaque
data:
  password: YWRtaW5AMTIzNA==
