apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range
spec:
  limits:
  - default: # sets up the default limits, any containers that don’t explicitly set these
      cpu: 2
      memory: 500Mib
    defaultRequest: # sets up the default requests, any containers that don’t explicitly set
      cpu: 1
      memory: 500Mib
    max:            # maximum limits that a container in a Pod can set
      cpu: 4
      memory: 4Gi
    min:            # minimum Requests that a container in a Pod can set.
      cpu: "250m"
      memory: 250Mib
    type: Container