apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-limit
spec:
  hard:
    requests.cpu: "500m" # in milli cores 1000m = 1 full core || 250m= 1/4th of a core
    requests.memory: 1Gi # 
    limits.cpu: "1000m"
    limits.memory: 2Gi