apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Chart.Name}}
  name: {{.Release.Name}}-{{.Chart.Name}}-{{.Values.service.name}}
  namespace: {{.Values.namespace.name}}
spec:
  type: {{.Values.service.type}}
  ports:
  - port: {{.Values.service.port}}
    protocol: TCP
    targetPort: 5432
  selector:
    app: {{.Chart.Name}}
